remove None values from TSFC parameters
I was getting:
  ...
  File "/home/mh1714/ffc-tsfc/src/tsfc/tsfc/fem.py", line 91, in epsilon
    return 10.0 * eval("1e-%d" % self.precision)
TypeError: %d format: a number is required, not NoneType

The test suite, however, still ran OK since that sets precision
explicitly.